version: "3.9"
 
services:
  backend:
    build: ./backend
    container_name: ieltsmill-backend
    ports:
      - "5050:6000"
    restart: always
 
  frontend:
    build: ./frontend
    container_name: ieltsmill-frontend
    ports:
      - "120:3000"
    depends_on:
      - backend
    restart: always